/**
 * This file was automatically generated by Nexus 0.11.6
 * Do not make changes to this file directly
 */

import * as context from "./context"


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  MutationType: "CREATED" | "DELETED" | "UPDATED"
  StatusEnum: "ACTIVE" | "DISABLED"
}

export interface NexusGenRootTypes {
  Post: { // root type
    content: string; // String!
    id: string; // ID!
    published: boolean; // Boolean!
    title: string; // String!
  }
  PostSubscriptionPayload: { // root type
    mutation: NexusGenEnums['MutationType']; // MutationType!
    node: NexusGenRootTypes['Post']; // Post!
    updatedFields: string[]; // [String!]!
  }
  Query: {};
  Subscription: {};
  Node: NexusGenRootTypes['Post'];
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  MutationType: NexusGenEnums['MutationType'];
  StatusEnum: NexusGenEnums['StatusEnum'];
}

export interface NexusGenFieldTypes {
  Post: { // field return type
    content: string; // String!
    id: string; // ID!
    published: boolean; // Boolean!
    title: string; // String!
  }
  PostSubscriptionPayload: { // field return type
    mutation: NexusGenEnums['MutationType']; // MutationType!
    node: NexusGenRootTypes['Post']; // Post!
    updatedFields: string[]; // [String!]!
  }
  Query: { // field return type
    post: NexusGenRootTypes['Post']; // Post!
  }
  Subscription: { // field return type
    post: NexusGenRootTypes['PostSubscriptionPayload']; // PostSubscriptionPayload!
  }
  Node: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenArgTypes {
  Query: {
    post: { // args
      name?: string | null; // String
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
  Node: "Post"
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Post" | "PostSubscriptionPayload" | "Query" | "Subscription";

export type NexusGenInputNames = never;

export type NexusGenEnumNames = "MutationType" | "StatusEnum";

export type NexusGenInterfaceNames = "Node";

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}